# typed: false
# frozen_string_literal: true

# Homebrew formula for the MAQPNA CLIs. GENERATED by hack/releasegen for
# v0.1.0 - do not edit by hand; see docs/releasing.md.
#
# Lives in the tap repository AzmxAI/homebrew-maqpna as Formula/maqpna.rb:
#   brew tap azmxai/maqpna
#   brew install azmxai/maqpna/maqpna
# Downloads are the GitHub release assets of AzmxAI/maqpna-releases.
class Maqpna < Formula
  desc "Sovereign runtime for AI agents on Kubernetes (maqpna, maqpna-sovereign CLIs)"
  homepage "https://maqpna.com"
  version "0.1.0"
  license "Apache-2.0"

  livecheck do
    url "https://github.com/AzmxAI/maqpna-releases"
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/AzmxAI/maqpna-releases/releases/download/v0.1.0/maqpna_0.1.0_darwin_arm64.zip"
      sha256 "df197137889f27c25ad7d9566d8323ed341980b9dccf540870b27fb5cf6d9176"
    end
    on_intel do
      url "https://github.com/AzmxAI/maqpna-releases/releases/download/v0.1.0/maqpna_0.1.0_darwin_amd64.zip"
      sha256 "7477f21c81800f7747fc333b75cddf3870500ba50c760ed82e750acd89f81e9d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/AzmxAI/maqpna-releases/releases/download/v0.1.0/maqpna_0.1.0_linux_arm64.tar.gz"
      sha256 "fd747e22c5e9f480c83bd94f190a32d746ef32495686ac4011e66ebbfd465a3e"
    end
    on_intel do
      url "https://github.com/AzmxAI/maqpna-releases/releases/download/v0.1.0/maqpna_0.1.0_linux_amd64.tar.gz"
      sha256 "ab42a88dc1becd36577b61bf1d8acd8ab55d992ce0840e992673259f787e33aa"
    end
  end

  def install
    bin.install "maqpna"
    bin.install "maqpna-sovereign"
  end

  def caveats
    <<~EOS
      The binaries are not notarized by Apple yet. Homebrew does not quarantine
      formula downloads, so they run as installed. If you copy them elsewhere
      and macOS blocks them, clear the quarantine attribute:
        xattr -d com.apple.quarantine #{opt_bin}/maqpna #{opt_bin}/maqpna-sovereign
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/maqpna version")
    assert_match version.to_s, shell_output("#{bin}/maqpna-sovereign version")
  end
end
