# typed: false
# frozen_string_literal: true

# Homebrew formula for the MAQPNA CLIs. GENERATED by hack/releasegen for
# v0.1.1 - do not edit by hand; see docs/releasing.md.
#
# Lives in the tap repository AzmxAI/homebrew-maqpna as Formula/maqpna.rb:
#   brew tap azmxai/maqpna
#   brew install azmxai/maqpna/maqpna
# Downloads are the GitHub release assets of AzmxAI/maqpna-releases.
class Maqpna < Formula
  desc "Sovereign runtime for AI agents: policy, approvals, DLP and audit"
  homepage "https://maqpna.com"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/AzmxAI/maqpna-releases/releases/download/v0.1.1/maqpna_0.1.1_darwin_arm64.zip"
      sha256 "2b4a2004977573feef577b83bfebaf1af8e463585bd1dbb9a30530527d62ecd5"
      resource "maqpna-install" do
        url "https://github.com/AzmxAI/maqpna-releases/releases/download/v0.1.1/maqpna-install_0.1.1_darwin_arm64.zip"
        sha256 "e4ea43b5281111bf42df0b71a3712bd1f460f9dcc87396b917be77ab4e490005"
      end
    end
    on_intel do
      url "https://github.com/AzmxAI/maqpna-releases/releases/download/v0.1.1/maqpna_0.1.1_darwin_amd64.zip"
      sha256 "3447cec566b77fac0b331164793b1304ffce2fe9941139559244b154b7deece7"
      resource "maqpna-install" do
        url "https://github.com/AzmxAI/maqpna-releases/releases/download/v0.1.1/maqpna-install_0.1.1_darwin_amd64.zip"
        sha256 "bbcde66bac9d17480fe639649b86904095ef6b17ef7bcf2d02cb5c9ad31e4734"
      end
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/AzmxAI/maqpna-releases/releases/download/v0.1.1/maqpna_0.1.1_linux_arm64.tar.gz"
      sha256 "e46d5a9476ffd4a1a5ac38dcd9a0e1ff81bd732dbb629e0e35362b6637ffa401"
      resource "maqpna-install" do
        url "https://github.com/AzmxAI/maqpna-releases/releases/download/v0.1.1/maqpna-install_0.1.1_linux_arm64.tar.gz"
        sha256 "5ea53618e06e7187a35c955b5446d7bea81408d1d7410b00dc459d0dfe3b8dd0"
      end
    end
    on_intel do
      url "https://github.com/AzmxAI/maqpna-releases/releases/download/v0.1.1/maqpna_0.1.1_linux_amd64.tar.gz"
      sha256 "2a1636a9c1ecd39b700f500c803beb71d77be05c9c9e40ab976442a3e902c304"
      resource "maqpna-install" do
        url "https://github.com/AzmxAI/maqpna-releases/releases/download/v0.1.1/maqpna-install_0.1.1_linux_amd64.tar.gz"
        sha256 "d90ad2ecd8f363f76b73b620a7a65123d348fe4f6b06a0809f650405d8d71274"
      end
    end
  end

  def install
    bin.install "maqpna"
    bin.install "maqpna-sovereign"
    # maqpna's lifecycle plugin (install, upgrade, rollback, uninstall,
    # preflight); maqpna runs it from next to itself.
    resource("maqpna-install").stage { bin.install "maqpna-install" }
  end

  def caveats
    <<~EOS
      Start a local MAQPNA (gateway, identity broker, test MCP server) with:
        maqpna dev up
      More: https://maqpna.com

      The binaries are not notarized by Apple yet. Homebrew does not quarantine
      formula downloads, so they run as installed. If you copy them elsewhere
      and macOS blocks them, clear the quarantine attribute:
        xattr -d com.apple.quarantine #{opt_bin}/maqpna #{opt_bin}/maqpna-install #{opt_bin}/maqpna-sovereign
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/maqpna version")
    assert_match version.to_s, shell_output("#{bin}/maqpna-sovereign version")
    assert_match version.to_s, shell_output("#{bin}/maqpna-install version")
  end
end
